---

resources:
- name: jhipster-git
  type: git
  source:
    uri: git@github.com:anoop2811/test-generator-jhipster-concourse-ci.git
    branch: master
    private_key: ((GIT_SSH_KEY.private_key))



- name: jhipster-image
  type: docker-image
  source:
    aws_access_key_id: ((AWS_ACCESS_KEY))
    aws_secret_access_key: ((AWS_SECRET_ACCESS_KEY))
    repository: /


jobs:
- name: unit-test
  plan:
  - get: jhipster-git
    trigger: true
  - task: gradle-test-task
    file: jhipster-git/ci/concourse/tasks/gradle-task.yml
    params:
      GRADLE_ARGS: clean test

- name: ui-test
  plan:
  - get: jhipster-git
    trigger: true
  - task: gradle-test-task
    file: jhipster-git/ci/concourse/tasks/gradle-task.yml
    params:
      GRADLE_ARGS: clean yarn_install yarn_test
- name: integration-test
  plan:
  - get: jhipster-git
    trigger: true
  - task: gradle-test-task
    file: jhipster-git/ci/concourse/tasks/gradle-task.yml
    params:
      GRADLE_ARGS: clean cucumberTest


- name: build
  plan:
  - get: jhipster-git
    trigger: true
    passed: [unit-test,integration-test, ui-test]
  - task: gradle-build-task
    file: jhipster-git/ci/concourse/tasks/gradle-task.yml
    params:
      GRADLE_ARGS: build -x test
  - put: jhipster-image
    params:
      build: jhipster-build
      tag_file: jhipster-version-output/number
- name: deploy-staging
  plan:
  - get: jhipster-git
    trigger: true
    passed: [build]
  - task: deploy-task
    file: jhipster/ci/concourse/tasks/deploy-task.yml

